//
//  CCAccount.m
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import "CCAccount.h"

struct CCAccountDirtyProperties {
    unsigned int CCAccountDirtyPropertyCreatedAt:1;
    unsigned int CCAccountDirtyPropertyEmail:1;
    unsigned int CCAccountDirtyPropertyFirstName:1;
    unsigned int CCAccountDirtyPropertyFullName:1;
    unsigned int CCAccountDirtyPropertyIdentifier:1;
    unsigned int CCAccountDirtyPropertyLastName:1;
    unsigned int CCAccountDirtyPropertyPhoneNumber:1;
    unsigned int CCAccountDirtyPropertyUpdatedAt:1;
};

@interface CCAccount ()
@property (nonatomic, assign, readwrite) struct CCAccountDirtyProperties accountDirtyProperties;
@end

@interface CCAccountBuilder ()
@property (nonatomic, assign, readwrite) struct CCAccountDirtyProperties accountDirtyProperties;
@end

@implementation CCAccount
+ (NSString *)className
{
    return @"CCAccount";
}
+ (NSString *)polymorphicTypeIdentifier
{
    return @"account";
}
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary
{
    return [[self alloc] initWithModelDictionary:dictionary];
}
- (instancetype)init
{
    return [self initWithModelDictionary:@{}];
}
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary
{
    NSParameterAssert(modelDictionary);
    if (!modelDictionary) {
        return self;
    }
    if (!(self = [super init])) {
        return self;
    }
        {
            __unsafe_unretained id value = modelDictionary[@"created_at"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_createdAt = [[NSValueTransformer valueTransformerForName:kPlankDateValueTransformerKey] transformedValue:value];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyCreatedAt = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"email"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_email = [value copy];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyEmail = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"first_name"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_firstName = [value copy];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyFirstName = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"full_name"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_fullName = [value copy];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyFullName = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"id"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_identifier = [value integerValue];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyIdentifier = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"last_name"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_lastName = [value copy];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyLastName = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"phone_number"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_phoneNumber = [value copy];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyPhoneNumber = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"updated_at"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_updatedAt = [[NSValueTransformer valueTransformerForName:kPlankDateValueTransformerKey] transformedValue:value];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt = 1;
            }
        }
    if ([self class] == [CCAccount class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(PlankModelInitTypeDefault) }];
    }
    return self;
}
- (instancetype)initWithBuilder:(CCAccountBuilder *)builder
{
    NSParameterAssert(builder);
    return [self initWithBuilder:builder initType:PlankModelInitTypeDefault];
}
- (instancetype)initWithBuilder:(CCAccountBuilder *)builder initType:(PlankModelInitType)initType
{
    NSParameterAssert(builder);
    if (!(self = [super init])) {
        return self;
    }
    _createdAt = builder.createdAt;
    _email = builder.email;
    _firstName = builder.firstName;
    _fullName = builder.fullName;
    _identifier = builder.identifier;
    _lastName = builder.lastName;
    _phoneNumber = builder.phoneNumber;
    _updatedAt = builder.updatedAt;
    _accountDirtyProperties = builder.accountDirtyProperties;
    if ([self class] == [CCAccount class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(initType) }];
    }
    return self;
}
- (NSString *)debugDescription
{
    NSArray<NSString *> *parentDebugDescription = [[super debugDescription] componentsSeparatedByString:@"\n"];
    NSMutableArray *descriptionFields = [NSMutableArray arrayWithCapacity:8];
    [descriptionFields addObject:parentDebugDescription];
    struct CCAccountDirtyProperties props = _accountDirtyProperties;
    if (props.CCAccountDirtyPropertyCreatedAt) {
        [descriptionFields addObject:[@"_createdAt = " stringByAppendingFormat:@"%@", _createdAt]];
    }
    if (props.CCAccountDirtyPropertyEmail) {
        [descriptionFields addObject:[@"_email = " stringByAppendingFormat:@"%@", _email]];
    }
    if (props.CCAccountDirtyPropertyFirstName) {
        [descriptionFields addObject:[@"_firstName = " stringByAppendingFormat:@"%@", _firstName]];
    }
    if (props.CCAccountDirtyPropertyFullName) {
        [descriptionFields addObject:[@"_fullName = " stringByAppendingFormat:@"%@", _fullName]];
    }
    if (props.CCAccountDirtyPropertyIdentifier) {
        [descriptionFields addObject:[@"_identifier = " stringByAppendingFormat:@"%@", @(_identifier)]];
    }
    if (props.CCAccountDirtyPropertyLastName) {
        [descriptionFields addObject:[@"_lastName = " stringByAppendingFormat:@"%@", _lastName]];
    }
    if (props.CCAccountDirtyPropertyPhoneNumber) {
        [descriptionFields addObject:[@"_phoneNumber = " stringByAppendingFormat:@"%@", _phoneNumber]];
    }
    if (props.CCAccountDirtyPropertyUpdatedAt) {
        [descriptionFields addObject:[@"_updatedAt = " stringByAppendingFormat:@"%@", _updatedAt]];
    }
    return [NSString stringWithFormat:@"CCAccount = {\n%@\n}", debugDescriptionForFields(descriptionFields)];
}
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCAccountBuilder *builder))block
{
    NSParameterAssert(block);
    CCAccountBuilder *builder = [[CCAccountBuilder alloc] initWithModel:self];
    block(builder);
    return [builder build];
}
- (BOOL)isEqual:(id)anObject
{
    if (self == anObject) {
        return YES;
    }
    if ([anObject isKindOfClass:[CCAccount class]] == NO) {
        return NO;
    }
    return [self isEqualToAccount:anObject];
}
- (BOOL)isEqualToAccount:(CCAccount *)anObject
{
    return (
        (anObject != nil) &&
        (_identifier == anObject.identifier) &&
        (_createdAt == anObject.createdAt || [_createdAt isEqualToDate:anObject.createdAt]) &&
        (_email == anObject.email || [_email isEqualToString:anObject.email]) &&
        (_firstName == anObject.firstName || [_firstName isEqualToString:anObject.firstName]) &&
        (_fullName == anObject.fullName || [_fullName isEqualToString:anObject.fullName]) &&
        (_lastName == anObject.lastName || [_lastName isEqualToString:anObject.lastName]) &&
        (_phoneNumber == anObject.phoneNumber || [_phoneNumber isEqualToString:anObject.phoneNumber]) &&
        (_updatedAt == anObject.updatedAt || [_updatedAt isEqualToDate:anObject.updatedAt])
    );
}
- (NSUInteger)hash
{
    NSUInteger subhashes[] = {
        17,
        [_createdAt hash],
        [_email hash],
        [_firstName hash],
        [_fullName hash],
        (NSUInteger)_identifier,
        [_lastName hash],
        [_phoneNumber hash],
        [_updatedAt hash]
    };
    return PINIntegerArrayHash(subhashes, sizeof(subhashes) / sizeof(subhashes[0]));
}
- (instancetype)mergeWithModel:(CCAccount *)modelObject
{
    return [self mergeWithModel:modelObject initType:PlankModelInitTypeFromMerge];
}
- (instancetype)mergeWithModel:(CCAccount *)modelObject initType:(PlankModelInitType)initType
{
    NSParameterAssert(modelObject);
    CCAccountBuilder *builder = [[CCAccountBuilder alloc] initWithModel:self];
    [builder mergeWithModel:modelObject];
    return [[CCAccount alloc] initWithBuilder:builder initType:initType];
}
- (NSDictionary *)dictionaryObjectRepresentation
{
    NSMutableDictionary *dict = [[NSMutableDictionary alloc] initWithCapacity:8];
    if (_accountDirtyProperties.CCAccountDirtyPropertyCreatedAt) {
        if (_createdAt != (id)kCFNull) {
            NSValueTransformer *valueTransformer = [NSValueTransformer valueTransformerForName:kPlankDateValueTransformerKey];
            if ([[valueTransformer class] allowsReverseTransformation]) {
                [dict setObject:[valueTransformer reverseTransformedValue:_createdAt] forKey:@"created_at"];
            } else {
                [dict setObject:[NSNull null] forKey:@"created_at"];
            }
        } else {
            [dict setObject:[NSNull null] forKey:@"created_at"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyEmail) {
        if (_email != (id)kCFNull) {
            [dict setObject:_email forKey:@"email"];
        } else {
            [dict setObject:[NSNull null] forKey:@"email"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyFirstName) {
        if (_firstName != (id)kCFNull) {
            [dict setObject:_firstName forKey:@"first_name"];
        } else {
            [dict setObject:[NSNull null] forKey:@"first_name"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyFullName) {
        if (_fullName != (id)kCFNull) {
            [dict setObject:_fullName forKey:@"full_name"];
        } else {
            [dict setObject:[NSNull null] forKey:@"full_name"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyIdentifier) {
        [dict setObject:@(_identifier) forKey: @"id"];
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyLastName) {
        if (_lastName != (id)kCFNull) {
            [dict setObject:_lastName forKey:@"last_name"];
        } else {
            [dict setObject:[NSNull null] forKey:@"last_name"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyPhoneNumber) {
        if (_phoneNumber != (id)kCFNull) {
            [dict setObject:_phoneNumber forKey:@"phone_number"];
        } else {
            [dict setObject:[NSNull null] forKey:@"phone_number"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt) {
        if (_updatedAt != (id)kCFNull) {
            NSValueTransformer *valueTransformer = [NSValueTransformer valueTransformerForName:kPlankDateValueTransformerKey];
            if ([[valueTransformer class] allowsReverseTransformation]) {
                [dict setObject:[valueTransformer reverseTransformedValue:_updatedAt] forKey:@"updated_at"];
            } else {
                [dict setObject:[NSNull null] forKey:@"updated_at"];
            }
        } else {
            [dict setObject:[NSNull null] forKey:@"updated_at"];
        }
    }
    return dict;
}
#pragma mark - NSCopying
- (id)copyWithZone:(NSZone *)zone
{
    return self;
}
#pragma mark - NSSecureCoding
+ (BOOL)supportsSecureCoding
{
    return YES;
}
- (instancetype)initWithCoder:(NSCoder *)aDecoder
{
    if (!(self = [super init])) {
        return self;
    }
    _createdAt = [aDecoder decodeObjectOfClass:[NSDate class] forKey:@"created_at"];
    _email = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"email"];
    _firstName = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"first_name"];
    _fullName = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"full_name"];
    _identifier = [aDecoder decodeIntegerForKey:@"id"];
    _lastName = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"last_name"];
    _phoneNumber = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"phone_number"];
    _updatedAt = [aDecoder decodeObjectOfClass:[NSDate class] forKey:@"updated_at"];
    _accountDirtyProperties.CCAccountDirtyPropertyCreatedAt = [aDecoder decodeIntForKey:@"created_at_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyEmail = [aDecoder decodeIntForKey:@"email_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyFirstName = [aDecoder decodeIntForKey:@"first_name_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyFullName = [aDecoder decodeIntForKey:@"full_name_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyIdentifier = [aDecoder decodeIntForKey:@"id_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyLastName = [aDecoder decodeIntForKey:@"last_name_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyPhoneNumber = [aDecoder decodeIntForKey:@"phone_number_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt = [aDecoder decodeIntForKey:@"updated_at_dirty_property"] & 0x1;
    if ([self class] == [CCAccount class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(PlankModelInitTypeDefault) }];
    }
    return self;
}
- (void)encodeWithCoder:(NSCoder *)aCoder
{
    [aCoder encodeObject:self.createdAt forKey:@"created_at"];
    [aCoder encodeObject:self.email forKey:@"email"];
    [aCoder encodeObject:self.firstName forKey:@"first_name"];
    [aCoder encodeObject:self.fullName forKey:@"full_name"];
    [aCoder encodeInteger:self.identifier forKey:@"id"];
    [aCoder encodeObject:self.lastName forKey:@"last_name"];
    [aCoder encodeObject:self.phoneNumber forKey:@"phone_number"];
    [aCoder encodeObject:self.updatedAt forKey:@"updated_at"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyCreatedAt forKey:@"created_at_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyEmail forKey:@"email_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyFirstName forKey:@"first_name_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyFullName forKey:@"full_name_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyIdentifier forKey:@"id_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyLastName forKey:@"last_name_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyPhoneNumber forKey:@"phone_number_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt forKey:@"updated_at_dirty_property"];
}
@end

@implementation CCAccountBuilder
- (instancetype)initWithModel:(CCAccount *)modelObject
{
    NSParameterAssert(modelObject);
    if (!(self = [super init])) {
        return self;
    }
    struct CCAccountDirtyProperties accountDirtyProperties = modelObject.accountDirtyProperties;
    if (accountDirtyProperties.CCAccountDirtyPropertyCreatedAt) {
        _createdAt = modelObject.createdAt;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyEmail) {
        _email = modelObject.email;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyFirstName) {
        _firstName = modelObject.firstName;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyFullName) {
        _fullName = modelObject.fullName;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyIdentifier) {
        _identifier = modelObject.identifier;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyLastName) {
        _lastName = modelObject.lastName;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyPhoneNumber) {
        _phoneNumber = modelObject.phoneNumber;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt) {
        _updatedAt = modelObject.updatedAt;
    }
    _accountDirtyProperties = accountDirtyProperties;
    return self;
}
- (CCAccount *)build
{
    return [[CCAccount alloc] initWithBuilder:self];
}
- (void)mergeWithModel:(CCAccount *)modelObject
{
    NSParameterAssert(modelObject);
    CCAccountBuilder *builder = self;
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyCreatedAt) {
        builder.createdAt = modelObject.createdAt;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyEmail) {
        builder.email = modelObject.email;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyFirstName) {
        builder.firstName = modelObject.firstName;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyFullName) {
        builder.fullName = modelObject.fullName;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyIdentifier) {
        builder.identifier = modelObject.identifier;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyLastName) {
        builder.lastName = modelObject.lastName;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyPhoneNumber) {
        builder.phoneNumber = modelObject.phoneNumber;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt) {
        builder.updatedAt = modelObject.updatedAt;
    }
}
- (void)setCreatedAt:(NSDate *)createdAt
{
    _createdAt = [createdAt copy];
    _accountDirtyProperties.CCAccountDirtyPropertyCreatedAt = 1;
}
- (void)setEmail:(NSString *)email
{
    _email = [email copy];
    _accountDirtyProperties.CCAccountDirtyPropertyEmail = 1;
}
- (void)setFirstName:(NSString *)firstName
{
    _firstName = [firstName copy];
    _accountDirtyProperties.CCAccountDirtyPropertyFirstName = 1;
}
- (void)setFullName:(NSString *)fullName
{
    _fullName = [fullName copy];
    _accountDirtyProperties.CCAccountDirtyPropertyFullName = 1;
}
- (void)setIdentifier:(NSInteger)identifier
{
    _identifier = identifier;
    _accountDirtyProperties.CCAccountDirtyPropertyIdentifier = 1;
}
- (void)setLastName:(NSString *)lastName
{
    _lastName = [lastName copy];
    _accountDirtyProperties.CCAccountDirtyPropertyLastName = 1;
}
- (void)setPhoneNumber:(NSString *)phoneNumber
{
    _phoneNumber = [phoneNumber copy];
    _accountDirtyProperties.CCAccountDirtyPropertyPhoneNumber = 1;
}
- (void)setUpdatedAt:(NSDate *)updatedAt
{
    _updatedAt = [updatedAt copy];
    _accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt = 1;
}
@end
