//
//  CCAccount.m
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import "CCAccount.h"
#import "CCEmail.h"
#import "CCPhone.h"
#import "CCProfilePicture.h"

struct CCAccountDirtyProperties {
    unsigned int CCAccountDirtyPropertyCreatedAt:1;
    unsigned int CCAccountDirtyPropertyEmails:1;
    unsigned int CCAccountDirtyPropertyFirstName:1;
    unsigned int CCAccountDirtyPropertyFullName:1;
    unsigned int CCAccountDirtyPropertyIdentifier:1;
    unsigned int CCAccountDirtyPropertyLastName:1;
    unsigned int CCAccountDirtyPropertyPhones:1;
    unsigned int CCAccountDirtyPropertyProfilePicture:1;
    unsigned int CCAccountDirtyPropertyUpdatedAt:1;
};

@interface CCAccount ()
@property (nonatomic, assign, readwrite) struct CCAccountDirtyProperties accountDirtyProperties;
@end

@interface CCAccountBuilder ()
@property (nonatomic, assign, readwrite) struct CCAccountDirtyProperties accountDirtyProperties;
@end

@implementation CCAccount
+ (NSString *)className
{
    return @"CCAccount";
}
+ (NSString *)polymorphicTypeIdentifier
{
    return @"account";
}
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary
{
    return [[self alloc] initWithModelDictionary:dictionary];
}
- (instancetype)init
{
    return [self initWithModelDictionary:@{}];
}
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary
{
    NSParameterAssert(modelDictionary);
    if (!modelDictionary) {
        return self;
    }
    if (!(self = [super init])) {
        return self;
    }
        {
            __unsafe_unretained id value = modelDictionary[@"created_at"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_createdAt = [[NSValueTransformer valueTransformerForName:kPlankDateValueTransformerKey] transformedValue:value];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyCreatedAt = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"emails"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    NSArray *items = value;
                    NSMutableArray *result0 = [NSMutableArray arrayWithCapacity:items.count];
                    for (id obj0 in items) {
                        if (obj0 != (id)kCFNull) {
                            id tmp0 = nil;
                            tmp0 = [CCEmail modelObjectWithDictionary:obj0];
                            if (tmp0 != nil) {
                                [result0 addObject:tmp0];
                            }
                        }
                    }
                    self->_emails = result0;
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyEmails = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"first_name"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_firstName = [value copy];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyFirstName = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"full_name"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_fullName = [value copy];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyFullName = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"id"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_identifier = [value integerValue];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyIdentifier = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"last_name"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_lastName = [value copy];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyLastName = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"phones"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    NSArray *items = value;
                    NSMutableArray *result0 = [NSMutableArray arrayWithCapacity:items.count];
                    for (id obj0 in items) {
                        if (obj0 != (id)kCFNull) {
                            id tmp0 = nil;
                            tmp0 = [CCPhone modelObjectWithDictionary:obj0];
                            if (tmp0 != nil) {
                                [result0 addObject:tmp0];
                            }
                        }
                    }
                    self->_phones = result0;
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyPhones = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"profile_picture"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_profilePicture = [CCProfilePicture modelObjectWithDictionary:value];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyProfilePicture = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"updated_at"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_updatedAt = [[NSValueTransformer valueTransformerForName:kPlankDateValueTransformerKey] transformedValue:value];
                }
                self->_accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt = 1;
            }
        }
    if ([self class] == [CCAccount class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(PlankModelInitTypeDefault) }];
    }
    return self;
}
- (instancetype)initWithBuilder:(CCAccountBuilder *)builder
{
    NSParameterAssert(builder);
    return [self initWithBuilder:builder initType:PlankModelInitTypeDefault];
}
- (instancetype)initWithBuilder:(CCAccountBuilder *)builder initType:(PlankModelInitType)initType
{
    NSParameterAssert(builder);
    if (!(self = [super init])) {
        return self;
    }
    _createdAt = builder.createdAt;
    _emails = builder.emails;
    _firstName = builder.firstName;
    _fullName = builder.fullName;
    _identifier = builder.identifier;
    _lastName = builder.lastName;
    _phones = builder.phones;
    _profilePicture = builder.profilePicture;
    _updatedAt = builder.updatedAt;
    _accountDirtyProperties = builder.accountDirtyProperties;
    if ([self class] == [CCAccount class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(initType) }];
    }
    return self;
}
- (NSString *)debugDescription
{
    NSArray<NSString *> *parentDebugDescription = [[super debugDescription] componentsSeparatedByString:@"\n"];
    NSMutableArray *descriptionFields = [NSMutableArray arrayWithCapacity:9];
    [descriptionFields addObject:parentDebugDescription];
    struct CCAccountDirtyProperties props = _accountDirtyProperties;
    if (props.CCAccountDirtyPropertyCreatedAt) {
        [descriptionFields addObject:[@"_createdAt = " stringByAppendingFormat:@"%@", _createdAt]];
    }
    if (props.CCAccountDirtyPropertyEmails) {
        [descriptionFields addObject:[@"_emails = " stringByAppendingFormat:@"%@", _emails]];
    }
    if (props.CCAccountDirtyPropertyFirstName) {
        [descriptionFields addObject:[@"_firstName = " stringByAppendingFormat:@"%@", _firstName]];
    }
    if (props.CCAccountDirtyPropertyFullName) {
        [descriptionFields addObject:[@"_fullName = " stringByAppendingFormat:@"%@", _fullName]];
    }
    if (props.CCAccountDirtyPropertyIdentifier) {
        [descriptionFields addObject:[@"_identifier = " stringByAppendingFormat:@"%@", @(_identifier)]];
    }
    if (props.CCAccountDirtyPropertyLastName) {
        [descriptionFields addObject:[@"_lastName = " stringByAppendingFormat:@"%@", _lastName]];
    }
    if (props.CCAccountDirtyPropertyPhones) {
        [descriptionFields addObject:[@"_phones = " stringByAppendingFormat:@"%@", _phones]];
    }
    if (props.CCAccountDirtyPropertyProfilePicture) {
        [descriptionFields addObject:[@"_profilePicture = " stringByAppendingFormat:@"%@", _profilePicture]];
    }
    if (props.CCAccountDirtyPropertyUpdatedAt) {
        [descriptionFields addObject:[@"_updatedAt = " stringByAppendingFormat:@"%@", _updatedAt]];
    }
    return [NSString stringWithFormat:@"CCAccount = {\n%@\n}", debugDescriptionForFields(descriptionFields)];
}
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCAccountBuilder *builder))block
{
    NSParameterAssert(block);
    CCAccountBuilder *builder = [[CCAccountBuilder alloc] initWithModel:self];
    block(builder);
    return [builder build];
}
- (BOOL)isEqual:(id)anObject
{
    if (self == anObject) {
        return YES;
    }
    if ([anObject isKindOfClass:[CCAccount class]] == NO) {
        return NO;
    }
    return [self isEqualToAccount:anObject];
}
- (BOOL)isEqualToAccount:(CCAccount *)anObject
{
    return (
        (anObject != nil) &&
        (_identifier == anObject.identifier) &&
        (_createdAt == anObject.createdAt || [_createdAt isEqualToDate:anObject.createdAt]) &&
        (_emails == anObject.emails || [_emails isEqualToArray:anObject.emails]) &&
        (_firstName == anObject.firstName || [_firstName isEqualToString:anObject.firstName]) &&
        (_fullName == anObject.fullName || [_fullName isEqualToString:anObject.fullName]) &&
        (_lastName == anObject.lastName || [_lastName isEqualToString:anObject.lastName]) &&
        (_phones == anObject.phones || [_phones isEqualToArray:anObject.phones]) &&
        (_profilePicture == anObject.profilePicture || [_profilePicture isEqual:anObject.profilePicture]) &&
        (_updatedAt == anObject.updatedAt || [_updatedAt isEqualToDate:anObject.updatedAt])
    );
}
- (NSUInteger)hash
{
    NSUInteger subhashes[] = {
        17,
        [_createdAt hash],
        [_emails hash],
        [_firstName hash],
        [_fullName hash],
        (NSUInteger)_identifier,
        [_lastName hash],
        [_phones hash],
        [_profilePicture hash],
        [_updatedAt hash]
    };
    return PINIntegerArrayHash(subhashes, sizeof(subhashes) / sizeof(subhashes[0]));
}
- (instancetype)mergeWithModel:(CCAccount *)modelObject
{
    return [self mergeWithModel:modelObject initType:PlankModelInitTypeFromMerge];
}
- (instancetype)mergeWithModel:(CCAccount *)modelObject initType:(PlankModelInitType)initType
{
    NSParameterAssert(modelObject);
    CCAccountBuilder *builder = [[CCAccountBuilder alloc] initWithModel:self];
    [builder mergeWithModel:modelObject];
    return [[CCAccount alloc] initWithBuilder:builder initType:initType];
}
- (NSDictionary *)dictionaryObjectRepresentation
{
    NSMutableDictionary *dict = [[NSMutableDictionary alloc] initWithCapacity:9];
    if (_accountDirtyProperties.CCAccountDirtyPropertyCreatedAt) {
        if (_createdAt != (id)kCFNull) {
            NSValueTransformer *valueTransformer = [NSValueTransformer valueTransformerForName:kPlankDateValueTransformerKey];
            if ([[valueTransformer class] allowsReverseTransformation]) {
                [dict setObject:[valueTransformer reverseTransformedValue:_createdAt] forKey:@"created_at"];
            } else {
                [dict setObject:[NSNull null] forKey:@"created_at"];
            }
        } else {
            [dict setObject:[NSNull null] forKey:@"created_at"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyEmails) {
        if (_emails != (id)kCFNull) {
            __auto_type items0 = _emails;
            NSMutableArray *result0 = [NSMutableArray arrayWithCapacity:items0.count];
            for (CCEmail * obj0 in items0) {
                [result0 addObject:[obj0 dictionaryObjectRepresentation]];
            }
            [dict setObject:result0 forKey:@"emails"];
        } else {
            [dict setObject:[NSNull null] forKey:@"emails"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyFirstName) {
        if (_firstName != (id)kCFNull) {
            [dict setObject:_firstName forKey:@"first_name"];
        } else {
            [dict setObject:[NSNull null] forKey:@"first_name"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyFullName) {
        if (_fullName != (id)kCFNull) {
            [dict setObject:_fullName forKey:@"full_name"];
        } else {
            [dict setObject:[NSNull null] forKey:@"full_name"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyIdentifier) {
        [dict setObject:@(_identifier) forKey: @"id"];
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyLastName) {
        if (_lastName != (id)kCFNull) {
            [dict setObject:_lastName forKey:@"last_name"];
        } else {
            [dict setObject:[NSNull null] forKey:@"last_name"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyPhones) {
        if (_phones != (id)kCFNull) {
            __auto_type items0 = _phones;
            NSMutableArray *result0 = [NSMutableArray arrayWithCapacity:items0.count];
            for (CCPhone * obj0 in items0) {
                [result0 addObject:[obj0 dictionaryObjectRepresentation]];
            }
            [dict setObject:result0 forKey:@"phones"];
        } else {
            [dict setObject:[NSNull null] forKey:@"phones"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyProfilePicture) {
        if (_profilePicture != (id)kCFNull) {
            [dict setObject:[_profilePicture dictionaryObjectRepresentation] forKey:@"profile_picture"];
        } else {
            [dict setObject:[NSNull null] forKey:@"profile_picture"];
        }
    }
    if (_accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt) {
        if (_updatedAt != (id)kCFNull) {
            NSValueTransformer *valueTransformer = [NSValueTransformer valueTransformerForName:kPlankDateValueTransformerKey];
            if ([[valueTransformer class] allowsReverseTransformation]) {
                [dict setObject:[valueTransformer reverseTransformedValue:_updatedAt] forKey:@"updated_at"];
            } else {
                [dict setObject:[NSNull null] forKey:@"updated_at"];
            }
        } else {
            [dict setObject:[NSNull null] forKey:@"updated_at"];
        }
    }
    return dict;
}
#pragma mark - NSCopying
- (id)copyWithZone:(NSZone *)zone
{
    return self;
}
#pragma mark - NSSecureCoding
+ (BOOL)supportsSecureCoding
{
    return YES;
}
- (instancetype)initWithCoder:(NSCoder *)aDecoder
{
    if (!(self = [super init])) {
        return self;
    }
    _createdAt = [aDecoder decodeObjectOfClass:[NSDate class] forKey:@"created_at"];
    _emails = [aDecoder decodeObjectOfClasses:[NSSet setWithArray:@[[CCEmail class], [NSArray class]]] forKey:@"emails"];
    _firstName = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"first_name"];
    _fullName = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"full_name"];
    _identifier = [aDecoder decodeIntegerForKey:@"id"];
    _lastName = [aDecoder decodeObjectOfClass:[NSString class] forKey:@"last_name"];
    _phones = [aDecoder decodeObjectOfClasses:[NSSet setWithArray:@[[CCPhone class], [NSArray class]]] forKey:@"phones"];
    _profilePicture = [aDecoder decodeObjectOfClass:[CCProfilePicture class] forKey:@"profile_picture"];
    _updatedAt = [aDecoder decodeObjectOfClass:[NSDate class] forKey:@"updated_at"];
    _accountDirtyProperties.CCAccountDirtyPropertyCreatedAt = [aDecoder decodeIntForKey:@"created_at_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyEmails = [aDecoder decodeIntForKey:@"emails_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyFirstName = [aDecoder decodeIntForKey:@"first_name_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyFullName = [aDecoder decodeIntForKey:@"full_name_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyIdentifier = [aDecoder decodeIntForKey:@"id_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyLastName = [aDecoder decodeIntForKey:@"last_name_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyPhones = [aDecoder decodeIntForKey:@"phones_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyProfilePicture = [aDecoder decodeIntForKey:@"profile_picture_dirty_property"] & 0x1;
    _accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt = [aDecoder decodeIntForKey:@"updated_at_dirty_property"] & 0x1;
    if ([self class] == [CCAccount class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(PlankModelInitTypeDefault) }];
    }
    return self;
}
- (void)encodeWithCoder:(NSCoder *)aCoder
{
    [aCoder encodeObject:self.createdAt forKey:@"created_at"];
    [aCoder encodeObject:self.emails forKey:@"emails"];
    [aCoder encodeObject:self.firstName forKey:@"first_name"];
    [aCoder encodeObject:self.fullName forKey:@"full_name"];
    [aCoder encodeInteger:self.identifier forKey:@"id"];
    [aCoder encodeObject:self.lastName forKey:@"last_name"];
    [aCoder encodeObject:self.phones forKey:@"phones"];
    [aCoder encodeObject:self.profilePicture forKey:@"profile_picture"];
    [aCoder encodeObject:self.updatedAt forKey:@"updated_at"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyCreatedAt forKey:@"created_at_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyEmails forKey:@"emails_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyFirstName forKey:@"first_name_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyFullName forKey:@"full_name_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyIdentifier forKey:@"id_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyLastName forKey:@"last_name_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyPhones forKey:@"phones_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyProfilePicture forKey:@"profile_picture_dirty_property"];
    [aCoder encodeInt:_accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt forKey:@"updated_at_dirty_property"];
}
@end

@implementation CCAccountBuilder
- (instancetype)initWithModel:(CCAccount *)modelObject
{
    NSParameterAssert(modelObject);
    if (!(self = [super init])) {
        return self;
    }
    struct CCAccountDirtyProperties accountDirtyProperties = modelObject.accountDirtyProperties;
    if (accountDirtyProperties.CCAccountDirtyPropertyCreatedAt) {
        _createdAt = modelObject.createdAt;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyEmails) {
        _emails = modelObject.emails;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyFirstName) {
        _firstName = modelObject.firstName;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyFullName) {
        _fullName = modelObject.fullName;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyIdentifier) {
        _identifier = modelObject.identifier;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyLastName) {
        _lastName = modelObject.lastName;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyPhones) {
        _phones = modelObject.phones;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyProfilePicture) {
        _profilePicture = modelObject.profilePicture;
    }
    if (accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt) {
        _updatedAt = modelObject.updatedAt;
    }
    _accountDirtyProperties = accountDirtyProperties;
    return self;
}
- (CCAccount *)build
{
    return [[CCAccount alloc] initWithBuilder:self];
}
- (void)mergeWithModel:(CCAccount *)modelObject
{
    NSParameterAssert(modelObject);
    CCAccountBuilder *builder = self;
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyCreatedAt) {
        builder.createdAt = modelObject.createdAt;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyEmails) {
        builder.emails = modelObject.emails;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyFirstName) {
        builder.firstName = modelObject.firstName;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyFullName) {
        builder.fullName = modelObject.fullName;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyIdentifier) {
        builder.identifier = modelObject.identifier;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyLastName) {
        builder.lastName = modelObject.lastName;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyPhones) {
        builder.phones = modelObject.phones;
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyProfilePicture) {
        id value = modelObject.profilePicture;
        if (value != nil) {
            if (builder.profilePicture) {
                builder.profilePicture = [builder.profilePicture mergeWithModel:value initType:PlankModelInitTypeFromSubmerge];
            } else {
                builder.profilePicture = value;
            }
        } else {
            builder.profilePicture = nil;
        }
    }
    if (modelObject.accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt) {
        builder.updatedAt = modelObject.updatedAt;
    }
}
- (void)setCreatedAt:(NSDate *)createdAt
{
    _createdAt = [createdAt copy];
    _accountDirtyProperties.CCAccountDirtyPropertyCreatedAt = 1;
}
- (void)setEmails:(NSArray<CCEmail *> *)emails
{
    _emails = emails;
    _accountDirtyProperties.CCAccountDirtyPropertyEmails = 1;
}
- (void)setFirstName:(NSString *)firstName
{
    _firstName = [firstName copy];
    _accountDirtyProperties.CCAccountDirtyPropertyFirstName = 1;
}
- (void)setFullName:(NSString *)fullName
{
    _fullName = [fullName copy];
    _accountDirtyProperties.CCAccountDirtyPropertyFullName = 1;
}
- (void)setIdentifier:(NSInteger)identifier
{
    _identifier = identifier;
    _accountDirtyProperties.CCAccountDirtyPropertyIdentifier = 1;
}
- (void)setLastName:(NSString *)lastName
{
    _lastName = [lastName copy];
    _accountDirtyProperties.CCAccountDirtyPropertyLastName = 1;
}
- (void)setPhones:(NSArray<CCPhone *> *)phones
{
    _phones = phones;
    _accountDirtyProperties.CCAccountDirtyPropertyPhones = 1;
}
- (void)setProfilePicture:(CCProfilePicture *)profilePicture
{
    _profilePicture = profilePicture;
    _accountDirtyProperties.CCAccountDirtyPropertyProfilePicture = 1;
}
- (void)setUpdatedAt:(NSDate *)updatedAt
{
    _updatedAt = [updatedAt copy];
    _accountDirtyProperties.CCAccountDirtyPropertyUpdatedAt = 1;
}
@end
