//
//  CCAddress.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class CCAddressBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface CCAddress : NSObject<NSCopying, NSSecureCoding>
@property (nullable, nonatomic, copy, readonly) NSString * state;
@property (nullable, nonatomic, copy, readonly) NSString * street2;
@property (nullable, nonatomic, copy, readonly) NSString * city;
@property (nullable, nonatomic, copy, readonly) NSString * street1;
@property (nullable, nonatomic, copy, readonly) NSString * zip;
@property (nullable, nonatomic, copy, readonly) NSString * country;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(CCAddressBuilder *)builder;
- (instancetype)initWithBuilder:(CCAddressBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCAddressBuilder *builder))block;
- (BOOL)isEqualToAddress:(CCAddress *)anObject;
- (instancetype)mergeWithModel:(CCAddress *)modelObject;
- (instancetype)mergeWithModel:(CCAddress *)modelObject initType:(PlankModelInitType)initType;
- (NSDictionary *)dictionaryObjectRepresentation;
@end

@interface CCAddressBuilder : NSObject
@property (nullable, nonatomic, copy, readwrite) NSString * state;
@property (nullable, nonatomic, copy, readwrite) NSString * street2;
@property (nullable, nonatomic, copy, readwrite) NSString * city;
@property (nullable, nonatomic, copy, readwrite) NSString * street1;
@property (nullable, nonatomic, copy, readwrite) NSString * zip;
@property (nullable, nonatomic, copy, readwrite) NSString * country;
- (instancetype)initWithModel:(CCAddress *)modelObject;
- (CCAddress *)build;
- (void)mergeWithModel:(CCAddress *)modelObject;
@end

NS_ASSUME_NONNULL_END
