//
//  CCContact.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class CCContactBuilder;
@class CCPersonalCard;
@class CCProfilePicture;
@class CCWorkCard;

NS_ASSUME_NONNULL_BEGIN

@interface CCContact : NSObject<NSCopying, NSSecureCoding>
@property (nonnull, nonatomic, copy, readonly) NSString * lastName;
@property (nullable, nonatomic, strong, readonly) CCWorkCard * workCard;
@property (nonatomic, assign, readonly) NSInteger identifier;
@property (nonnull, nonatomic, copy, readonly) NSDate * updatedAt;
@property (nonnull, nonatomic, copy, readonly) NSString * fullName;
@property (nonnull, nonatomic, copy, readonly) NSDate * createdAt;
@property (nonnull, nonatomic, copy, readonly) NSString * firstName;
@property (nullable, nonatomic, strong, readonly) CCProfilePicture * profilePicture;
@property (nullable, nonatomic, strong, readonly) CCPersonalCard * personalCard;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(CCContactBuilder *)builder;
- (instancetype)initWithBuilder:(CCContactBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCContactBuilder *builder))block;
- (BOOL)isEqualToContact:(CCContact *)anObject;
- (instancetype)mergeWithModel:(CCContact *)modelObject;
- (instancetype)mergeWithModel:(CCContact *)modelObject initType:(PlankModelInitType)initType;
- (NSDictionary *)dictionaryObjectRepresentation;
@end

@interface CCContactBuilder : NSObject
@property (nonnull, nonatomic, copy, readwrite) NSString * lastName;
@property (nullable, nonatomic, strong, readwrite) CCWorkCard * workCard;
@property (nonatomic, assign, readwrite) NSInteger identifier;
@property (nonnull, nonatomic, copy, readwrite) NSDate * updatedAt;
@property (nonnull, nonatomic, copy, readwrite) NSString * fullName;
@property (nonnull, nonatomic, copy, readwrite) NSDate * createdAt;
@property (nonnull, nonatomic, copy, readwrite) NSString * firstName;
@property (nullable, nonatomic, strong, readwrite) CCProfilePicture * profilePicture;
@property (nullable, nonatomic, strong, readwrite) CCPersonalCard * personalCard;
- (instancetype)initWithModel:(CCContact *)modelObject;
- (CCContact *)build;
- (void)mergeWithModel:(CCContact *)modelObject;
@end

NS_ASSUME_NONNULL_END
