//
//  CCEmail.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class CCEmailBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface CCEmail : NSObject<NSCopying, NSSecureCoding>
@property (nonnull, nonatomic, copy, readonly) NSString * address;
@property (nonatomic, assign, readonly) BOOL isPrimary;
@property (nonnull, nonatomic, copy, readonly) NSDate * updatedAt;
@property (nonatomic, assign, readonly) NSInteger identifier;
@property (nonnull, nonatomic, copy, readonly) NSString * type;
@property (nonnull, nonatomic, copy, readonly) NSDate * createdAt;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(CCEmailBuilder *)builder;
- (instancetype)initWithBuilder:(CCEmailBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCEmailBuilder *builder))block;
- (BOOL)isEqualToEmail:(CCEmail *)anObject;
- (instancetype)mergeWithModel:(CCEmail *)modelObject;
- (instancetype)mergeWithModel:(CCEmail *)modelObject initType:(PlankModelInitType)initType;
- (NSDictionary *)dictionaryObjectRepresentation;
@end

@interface CCEmailBuilder : NSObject
@property (nonnull, nonatomic, copy, readwrite) NSString * address;
@property (nonatomic, assign, readwrite) BOOL isPrimary;
@property (nonnull, nonatomic, copy, readwrite) NSDate * updatedAt;
@property (nonatomic, assign, readwrite) NSInteger identifier;
@property (nonnull, nonatomic, copy, readwrite) NSString * type;
@property (nonnull, nonatomic, copy, readwrite) NSDate * createdAt;
- (instancetype)initWithModel:(CCEmail *)modelObject;
- (CCEmail *)build;
- (void)mergeWithModel:(CCEmail *)modelObject;
@end

NS_ASSUME_NONNULL_END
