//
//  CCGroupPicture.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class CCGroupPictureBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface CCGroupPicture : NSObject<NSCopying, NSSecureCoding>
@property (nonnull, nonatomic, copy, readonly) NSURL * thumbNormal;
@property (nonnull, nonatomic, copy, readonly) NSURL * thumbBig;
@property (nonnull, nonatomic, copy, readonly) NSURL * original;
@property (nonnull, nonatomic, copy, readonly) NSURL * thumbMini;
@property (nonnull, nonatomic, copy, readonly) NSURL * thumbSmall;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(CCGroupPictureBuilder *)builder;
- (instancetype)initWithBuilder:(CCGroupPictureBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCGroupPictureBuilder *builder))block;
- (BOOL)isEqualToGroupPicture:(CCGroupPicture *)anObject;
- (instancetype)mergeWithModel:(CCGroupPicture *)modelObject;
- (instancetype)mergeWithModel:(CCGroupPicture *)modelObject initType:(PlankModelInitType)initType;
- (NSDictionary *)dictionaryObjectRepresentation;
@end

@interface CCGroupPictureBuilder : NSObject
@property (nonnull, nonatomic, copy, readwrite) NSURL * thumbNormal;
@property (nonnull, nonatomic, copy, readwrite) NSURL * thumbBig;
@property (nonnull, nonatomic, copy, readwrite) NSURL * original;
@property (nonnull, nonatomic, copy, readwrite) NSURL * thumbMini;
@property (nonnull, nonatomic, copy, readwrite) NSURL * thumbSmall;
- (instancetype)initWithModel:(CCGroupPicture *)modelObject;
- (CCGroupPicture *)build;
- (void)mergeWithModel:(CCGroupPicture *)modelObject;
@end

NS_ASSUME_NONNULL_END
