//
//  CCGroup.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class CCGroupBuilder;
@class CCGroupPicture;

NS_ASSUME_NONNULL_BEGIN

@interface CCGroup : NSObject<NSCopying, NSSecureCoding>
@property (nullable, nonatomic, strong, readonly) CCGroupPicture * picture;
@property (nonatomic, assign, readonly) BOOL isAdmin;
@property (nonnull, nonatomic, copy, readonly) NSString * name;
@property (nonnull, nonatomic, copy, readonly) NSDate * updatedAt;
@property (nonatomic, assign, readonly) NSInteger identifier;
@property (nonatomic, assign, readonly) NSInteger memberCount;
@property (nonnull, nonatomic, copy, readonly) NSDate * createdAt;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(CCGroupBuilder *)builder;
- (instancetype)initWithBuilder:(CCGroupBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCGroupBuilder *builder))block;
- (BOOL)isEqualToGroup:(CCGroup *)anObject;
- (instancetype)mergeWithModel:(CCGroup *)modelObject;
- (instancetype)mergeWithModel:(CCGroup *)modelObject initType:(PlankModelInitType)initType;
- (NSDictionary *)dictionaryObjectRepresentation;
@end

@interface CCGroupBuilder : NSObject
@property (nullable, nonatomic, strong, readwrite) CCGroupPicture * picture;
@property (nonatomic, assign, readwrite) BOOL isAdmin;
@property (nonnull, nonatomic, copy, readwrite) NSString * name;
@property (nonnull, nonatomic, copy, readwrite) NSDate * updatedAt;
@property (nonatomic, assign, readwrite) NSInteger identifier;
@property (nonatomic, assign, readwrite) NSInteger memberCount;
@property (nonnull, nonatomic, copy, readwrite) NSDate * createdAt;
- (instancetype)initWithModel:(CCGroup *)modelObject;
- (CCGroup *)build;
- (void)mergeWithModel:(CCGroup *)modelObject;
@end

NS_ASSUME_NONNULL_END
