//
//  CCGroupPicture.m
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import "CCGroupPicture.h"

struct CCGroupPictureDirtyProperties {
    unsigned int CCGroupPictureDirtyPropertyOriginal:1;
    unsigned int CCGroupPictureDirtyPropertyThumbBig:1;
    unsigned int CCGroupPictureDirtyPropertyThumbMini:1;
    unsigned int CCGroupPictureDirtyPropertyThumbNormal:1;
    unsigned int CCGroupPictureDirtyPropertyThumbSmall:1;
};

@interface CCGroupPicture ()
@property (nonatomic, assign, readwrite) struct CCGroupPictureDirtyProperties groupPictureDirtyProperties;
@end

@interface CCGroupPictureBuilder ()
@property (nonatomic, assign, readwrite) struct CCGroupPictureDirtyProperties groupPictureDirtyProperties;
@end

@implementation CCGroupPicture
+ (NSString *)className
{
    return @"CCGroupPicture";
}
+ (NSString *)polymorphicTypeIdentifier
{
    return @"group_picture";
}
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary
{
    return [[self alloc] initWithModelDictionary:dictionary];
}
- (instancetype)init
{
    return [self initWithModelDictionary:@{}];
}
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary
{
    NSParameterAssert(modelDictionary);
    if (!modelDictionary) {
        return self;
    }
    if (!(self = [super init])) {
        return self;
    }
        {
            __unsafe_unretained id value = modelDictionary[@"original"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_original = [NSURL URLWithString:value];
                }
                self->_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyOriginal = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"thumb_big"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_thumbBig = [NSURL URLWithString:value];
                }
                self->_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbBig = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"thumb_mini"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_thumbMini = [NSURL URLWithString:value];
                }
                self->_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbMini = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"thumb_normal"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_thumbNormal = [NSURL URLWithString:value];
                }
                self->_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbNormal = 1;
            }
        }
        {
            __unsafe_unretained id value = modelDictionary[@"thumb_small"]; // Collection will retain.
            if (value != nil) {
                if (value != (id)kCFNull) {
                    self->_thumbSmall = [NSURL URLWithString:value];
                }
                self->_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbSmall = 1;
            }
        }
    if ([self class] == [CCGroupPicture class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(PlankModelInitTypeDefault) }];
    }
    return self;
}
- (instancetype)initWithBuilder:(CCGroupPictureBuilder *)builder
{
    NSParameterAssert(builder);
    return [self initWithBuilder:builder initType:PlankModelInitTypeDefault];
}
- (instancetype)initWithBuilder:(CCGroupPictureBuilder *)builder initType:(PlankModelInitType)initType
{
    NSParameterAssert(builder);
    if (!(self = [super init])) {
        return self;
    }
    _original = builder.original;
    _thumbBig = builder.thumbBig;
    _thumbMini = builder.thumbMini;
    _thumbNormal = builder.thumbNormal;
    _thumbSmall = builder.thumbSmall;
    _groupPictureDirtyProperties = builder.groupPictureDirtyProperties;
    if ([self class] == [CCGroupPicture class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(initType) }];
    }
    return self;
}
- (NSString *)debugDescription
{
    NSArray<NSString *> *parentDebugDescription = [[super debugDescription] componentsSeparatedByString:@"\n"];
    NSMutableArray *descriptionFields = [NSMutableArray arrayWithCapacity:5];
    [descriptionFields addObject:parentDebugDescription];
    struct CCGroupPictureDirtyProperties props = _groupPictureDirtyProperties;
    if (props.CCGroupPictureDirtyPropertyOriginal) {
        [descriptionFields addObject:[@"_original = " stringByAppendingFormat:@"%@", _original]];
    }
    if (props.CCGroupPictureDirtyPropertyThumbBig) {
        [descriptionFields addObject:[@"_thumbBig = " stringByAppendingFormat:@"%@", _thumbBig]];
    }
    if (props.CCGroupPictureDirtyPropertyThumbMini) {
        [descriptionFields addObject:[@"_thumbMini = " stringByAppendingFormat:@"%@", _thumbMini]];
    }
    if (props.CCGroupPictureDirtyPropertyThumbNormal) {
        [descriptionFields addObject:[@"_thumbNormal = " stringByAppendingFormat:@"%@", _thumbNormal]];
    }
    if (props.CCGroupPictureDirtyPropertyThumbSmall) {
        [descriptionFields addObject:[@"_thumbSmall = " stringByAppendingFormat:@"%@", _thumbSmall]];
    }
    return [NSString stringWithFormat:@"CCGroupPicture = {\n%@\n}", debugDescriptionForFields(descriptionFields)];
}
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCGroupPictureBuilder *builder))block
{
    NSParameterAssert(block);
    CCGroupPictureBuilder *builder = [[CCGroupPictureBuilder alloc] initWithModel:self];
    block(builder);
    return [builder build];
}
- (BOOL)isEqual:(id)anObject
{
    if (self == anObject) {
        return YES;
    }
    if ([anObject isKindOfClass:[CCGroupPicture class]] == NO) {
        return NO;
    }
    return [self isEqualToGroupPicture:anObject];
}
- (BOOL)isEqualToGroupPicture:(CCGroupPicture *)anObject
{
    return (
        (anObject != nil) &&
        (_original == anObject.original || [_original isEqual:anObject.original]) &&
        (_thumbBig == anObject.thumbBig || [_thumbBig isEqual:anObject.thumbBig]) &&
        (_thumbMini == anObject.thumbMini || [_thumbMini isEqual:anObject.thumbMini]) &&
        (_thumbNormal == anObject.thumbNormal || [_thumbNormal isEqual:anObject.thumbNormal]) &&
        (_thumbSmall == anObject.thumbSmall || [_thumbSmall isEqual:anObject.thumbSmall])
    );
}
- (NSUInteger)hash
{
    NSUInteger subhashes[] = {
        17,
        [_original hash],
        [_thumbBig hash],
        [_thumbMini hash],
        [_thumbNormal hash],
        [_thumbSmall hash]
    };
    return PINIntegerArrayHash(subhashes, sizeof(subhashes) / sizeof(subhashes[0]));
}
- (instancetype)mergeWithModel:(CCGroupPicture *)modelObject
{
    return [self mergeWithModel:modelObject initType:PlankModelInitTypeFromMerge];
}
- (instancetype)mergeWithModel:(CCGroupPicture *)modelObject initType:(PlankModelInitType)initType
{
    NSParameterAssert(modelObject);
    CCGroupPictureBuilder *builder = [[CCGroupPictureBuilder alloc] initWithModel:self];
    [builder mergeWithModel:modelObject];
    return [[CCGroupPicture alloc] initWithBuilder:builder initType:initType];
}
- (NSDictionary *)dictionaryObjectRepresentation
{
    NSMutableDictionary *dict = [[NSMutableDictionary alloc] initWithCapacity:5];
    if (_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyOriginal) {
        if (_original != (id)kCFNull) {
            [dict setObject:[_original absoluteString] forKey:@"original"];
        } else {
            [dict setObject:[NSNull null] forKey:@"original"];
        }
    }
    if (_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbBig) {
        if (_thumbBig != (id)kCFNull) {
            [dict setObject:[_thumbBig absoluteString] forKey:@"thumb_big"];
        } else {
            [dict setObject:[NSNull null] forKey:@"thumb_big"];
        }
    }
    if (_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbMini) {
        if (_thumbMini != (id)kCFNull) {
            [dict setObject:[_thumbMini absoluteString] forKey:@"thumb_mini"];
        } else {
            [dict setObject:[NSNull null] forKey:@"thumb_mini"];
        }
    }
    if (_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbNormal) {
        if (_thumbNormal != (id)kCFNull) {
            [dict setObject:[_thumbNormal absoluteString] forKey:@"thumb_normal"];
        } else {
            [dict setObject:[NSNull null] forKey:@"thumb_normal"];
        }
    }
    if (_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbSmall) {
        if (_thumbSmall != (id)kCFNull) {
            [dict setObject:[_thumbSmall absoluteString] forKey:@"thumb_small"];
        } else {
            [dict setObject:[NSNull null] forKey:@"thumb_small"];
        }
    }
    return dict;
}
#pragma mark - NSCopying
- (id)copyWithZone:(NSZone *)zone
{
    return self;
}
#pragma mark - NSSecureCoding
+ (BOOL)supportsSecureCoding
{
    return YES;
}
- (instancetype)initWithCoder:(NSCoder *)aDecoder
{
    if (!(self = [super init])) {
        return self;
    }
    _original = [aDecoder decodeObjectOfClass:[NSURL class] forKey:@"original"];
    _thumbBig = [aDecoder decodeObjectOfClass:[NSURL class] forKey:@"thumb_big"];
    _thumbMini = [aDecoder decodeObjectOfClass:[NSURL class] forKey:@"thumb_mini"];
    _thumbNormal = [aDecoder decodeObjectOfClass:[NSURL class] forKey:@"thumb_normal"];
    _thumbSmall = [aDecoder decodeObjectOfClass:[NSURL class] forKey:@"thumb_small"];
    _groupPictureDirtyProperties.CCGroupPictureDirtyPropertyOriginal = [aDecoder decodeIntForKey:@"original_dirty_property"] & 0x1;
    _groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbBig = [aDecoder decodeIntForKey:@"thumb_big_dirty_property"] & 0x1;
    _groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbMini = [aDecoder decodeIntForKey:@"thumb_mini_dirty_property"] & 0x1;
    _groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbNormal = [aDecoder decodeIntForKey:@"thumb_normal_dirty_property"] & 0x1;
    _groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbSmall = [aDecoder decodeIntForKey:@"thumb_small_dirty_property"] & 0x1;
    if ([self class] == [CCGroupPicture class]) {
        [[NSNotificationCenter defaultCenter] postNotificationName:kPlankDidInitializeNotification object:self userInfo:@{ kPlankInitTypeKey : @(PlankModelInitTypeDefault) }];
    }
    return self;
}
- (void)encodeWithCoder:(NSCoder *)aCoder
{
    [aCoder encodeObject:self.original forKey:@"original"];
    [aCoder encodeObject:self.thumbBig forKey:@"thumb_big"];
    [aCoder encodeObject:self.thumbMini forKey:@"thumb_mini"];
    [aCoder encodeObject:self.thumbNormal forKey:@"thumb_normal"];
    [aCoder encodeObject:self.thumbSmall forKey:@"thumb_small"];
    [aCoder encodeInt:_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyOriginal forKey:@"original_dirty_property"];
    [aCoder encodeInt:_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbBig forKey:@"thumb_big_dirty_property"];
    [aCoder encodeInt:_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbMini forKey:@"thumb_mini_dirty_property"];
    [aCoder encodeInt:_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbNormal forKey:@"thumb_normal_dirty_property"];
    [aCoder encodeInt:_groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbSmall forKey:@"thumb_small_dirty_property"];
}
@end

@implementation CCGroupPictureBuilder
- (instancetype)initWithModel:(CCGroupPicture *)modelObject
{
    NSParameterAssert(modelObject);
    if (!(self = [super init])) {
        return self;
    }
    struct CCGroupPictureDirtyProperties groupPictureDirtyProperties = modelObject.groupPictureDirtyProperties;
    if (groupPictureDirtyProperties.CCGroupPictureDirtyPropertyOriginal) {
        _original = modelObject.original;
    }
    if (groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbBig) {
        _thumbBig = modelObject.thumbBig;
    }
    if (groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbMini) {
        _thumbMini = modelObject.thumbMini;
    }
    if (groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbNormal) {
        _thumbNormal = modelObject.thumbNormal;
    }
    if (groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbSmall) {
        _thumbSmall = modelObject.thumbSmall;
    }
    _groupPictureDirtyProperties = groupPictureDirtyProperties;
    return self;
}
- (CCGroupPicture *)build
{
    return [[CCGroupPicture alloc] initWithBuilder:self];
}
- (void)mergeWithModel:(CCGroupPicture *)modelObject
{
    NSParameterAssert(modelObject);
    CCGroupPictureBuilder *builder = self;
    if (modelObject.groupPictureDirtyProperties.CCGroupPictureDirtyPropertyOriginal) {
        builder.original = modelObject.original;
    }
    if (modelObject.groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbBig) {
        builder.thumbBig = modelObject.thumbBig;
    }
    if (modelObject.groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbMini) {
        builder.thumbMini = modelObject.thumbMini;
    }
    if (modelObject.groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbNormal) {
        builder.thumbNormal = modelObject.thumbNormal;
    }
    if (modelObject.groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbSmall) {
        builder.thumbSmall = modelObject.thumbSmall;
    }
}
- (void)setOriginal:(NSURL *)original
{
    _original = [original copy];
    _groupPictureDirtyProperties.CCGroupPictureDirtyPropertyOriginal = 1;
}
- (void)setThumbBig:(NSURL *)thumbBig
{
    _thumbBig = [thumbBig copy];
    _groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbBig = 1;
}
- (void)setThumbMini:(NSURL *)thumbMini
{
    _thumbMini = [thumbMini copy];
    _groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbMini = 1;
}
- (void)setThumbNormal:(NSURL *)thumbNormal
{
    _thumbNormal = [thumbNormal copy];
    _groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbNormal = 1;
}
- (void)setThumbSmall:(NSURL *)thumbSmall
{
    _thumbSmall = [thumbSmall copy];
    _groupPictureDirtyProperties.CCGroupPictureDirtyPropertyThumbSmall = 1;
}
@end
