//
//  CCPersonalCard.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class CCAddress;
@class CCPersonalCardBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface CCPersonalCard : NSObject<NSCopying, NSSecureCoding>
@property (nullable, nonatomic, copy, readonly) NSString * cellPhone;
@property (nullable, nonatomic, copy, readonly) NSString * homePhone;
@property (nullable, nonatomic, copy, readonly) NSString * email;
@property (nullable, nonatomic, strong, readonly) CCAddress * address;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(CCPersonalCardBuilder *)builder;
- (instancetype)initWithBuilder:(CCPersonalCardBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCPersonalCardBuilder *builder))block;
- (BOOL)isEqualToPersonalCard:(CCPersonalCard *)anObject;
- (instancetype)mergeWithModel:(CCPersonalCard *)modelObject;
- (instancetype)mergeWithModel:(CCPersonalCard *)modelObject initType:(PlankModelInitType)initType;
- (NSDictionary *)dictionaryObjectRepresentation;
@end

@interface CCPersonalCardBuilder : NSObject
@property (nullable, nonatomic, copy, readwrite) NSString * cellPhone;
@property (nullable, nonatomic, copy, readwrite) NSString * homePhone;
@property (nullable, nonatomic, copy, readwrite) NSString * email;
@property (nullable, nonatomic, strong, readwrite) CCAddress * address;
- (instancetype)initWithModel:(CCPersonalCard *)modelObject;
- (CCPersonalCard *)build;
- (void)mergeWithModel:(CCPersonalCard *)modelObject;
@end

NS_ASSUME_NONNULL_END
