//
//  CCProfilePicture.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class CCProfilePictureBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface CCProfilePicture : NSObject<NSCopying, NSSecureCoding>
@property (nonnull, nonatomic, copy, readonly) NSURL * thumbNormal;
@property (nonnull, nonatomic, copy, readonly) NSURL * thumbBig;
@property (nonnull, nonatomic, copy, readonly) NSURL * original;
@property (nonnull, nonatomic, copy, readonly) NSURL * thumbMini;
@property (nonnull, nonatomic, copy, readonly) NSURL * thumbSmall;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(CCProfilePictureBuilder *)builder;
- (instancetype)initWithBuilder:(CCProfilePictureBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCProfilePictureBuilder *builder))block;
- (BOOL)isEqualToProfilePicture:(CCProfilePicture *)anObject;
- (instancetype)mergeWithModel:(CCProfilePicture *)modelObject;
- (instancetype)mergeWithModel:(CCProfilePicture *)modelObject initType:(PlankModelInitType)initType;
- (NSDictionary *)dictionaryObjectRepresentation;
@end

@interface CCProfilePictureBuilder : NSObject
@property (nonnull, nonatomic, copy, readwrite) NSURL * thumbNormal;
@property (nonnull, nonatomic, copy, readwrite) NSURL * thumbBig;
@property (nonnull, nonatomic, copy, readwrite) NSURL * original;
@property (nonnull, nonatomic, copy, readwrite) NSURL * thumbMini;
@property (nonnull, nonatomic, copy, readwrite) NSURL * thumbSmall;
- (instancetype)initWithModel:(CCProfilePicture *)modelObject;
- (CCProfilePicture *)build;
- (void)mergeWithModel:(CCProfilePicture *)modelObject;
@end

NS_ASSUME_NONNULL_END
