//
//  CCToken.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class CCTokenBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface CCToken : NSObject<NSCopying, NSSecureCoding>
@property (nonnull, nonatomic, copy, readonly) NSString * refreshToken;
@property (nonnull, nonatomic, copy, readonly) NSString * tokenType;
@property (nonnull, nonatomic, copy, readonly) NSString * accessToken;
@property (nonatomic, assign, readonly) NSInteger expiresIn;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(CCTokenBuilder *)builder;
- (instancetype)initWithBuilder:(CCTokenBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCTokenBuilder *builder))block;
- (BOOL)isEqualToToken:(CCToken *)anObject;
- (instancetype)mergeWithModel:(CCToken *)modelObject;
- (instancetype)mergeWithModel:(CCToken *)modelObject initType:(PlankModelInitType)initType;
- (NSDictionary *)dictionaryObjectRepresentation;
@end

@interface CCTokenBuilder : NSObject
@property (nonnull, nonatomic, copy, readwrite) NSString * refreshToken;
@property (nonnull, nonatomic, copy, readwrite) NSString * tokenType;
@property (nonnull, nonatomic, copy, readwrite) NSString * accessToken;
@property (nonatomic, assign, readwrite) NSInteger expiresIn;
- (instancetype)initWithModel:(CCToken *)modelObject;
- (CCToken *)build;
- (void)mergeWithModel:(CCToken *)modelObject;
@end

NS_ASSUME_NONNULL_END
