//
//  CCUser.h
//  Autogenerated by plank
//
//  DO NOT EDIT - EDITS WILL BE OVERWRITTEN
//  @generated
//

#import <Foundation/Foundation.h>
#import "PlankModelRuntime.h"
@class CCProfilePicture;
@class CCUserBuilder;

NS_ASSUME_NONNULL_BEGIN

@interface CCUser : NSObject<NSCopying, NSSecureCoding>
@property (nonnull, nonatomic, copy, readonly) NSString * lastName;
@property (nonnull, nonatomic, copy, readonly) NSDate * updatedAt;
@property (nonatomic, assign, readonly) NSInteger identifier;
@property (nonnull, nonatomic, copy, readonly) NSString * fullName;
@property (nonnull, nonatomic, copy, readonly) NSString * firstName;
@property (nonnull, nonatomic, copy, readonly) NSDate * createdAt;
@property (nullable, nonatomic, strong, readonly) CCProfilePicture * profilePicture;
+ (NSString *)className;
+ (NSString *)polymorphicTypeIdentifier;
+ (instancetype)modelObjectWithDictionary:(NSDictionary *)dictionary;
- (instancetype)initWithModelDictionary:(NS_VALID_UNTIL_END_OF_SCOPE NSDictionary *)modelDictionary;
- (instancetype)initWithBuilder:(CCUserBuilder *)builder;
- (instancetype)initWithBuilder:(CCUserBuilder *)builder initType:(PlankModelInitType)initType;
- (instancetype)copyWithBlock:(PLANK_NOESCAPE void (^)(CCUserBuilder *builder))block;
- (BOOL)isEqualToUser:(CCUser *)anObject;
- (instancetype)mergeWithModel:(CCUser *)modelObject;
- (instancetype)mergeWithModel:(CCUser *)modelObject initType:(PlankModelInitType)initType;
- (NSDictionary *)dictionaryObjectRepresentation;
@end

@interface CCUserBuilder : NSObject
@property (nonnull, nonatomic, copy, readwrite) NSString * lastName;
@property (nonnull, nonatomic, copy, readwrite) NSDate * updatedAt;
@property (nonatomic, assign, readwrite) NSInteger identifier;
@property (nonnull, nonatomic, copy, readwrite) NSString * fullName;
@property (nonnull, nonatomic, copy, readwrite) NSString * firstName;
@property (nonnull, nonatomic, copy, readwrite) NSDate * createdAt;
@property (nullable, nonatomic, strong, readwrite) CCProfilePicture * profilePicture;
- (instancetype)initWithModel:(CCUser *)modelObject;
- (CCUser *)build;
- (void)mergeWithModel:(CCUser *)modelObject;
@end

NS_ASSUME_NONNULL_END
